README.md + logo picture
beyond-io/joboard pull request #8
Opened 2020-11-12 16:22 UTC by Varditli

Edited the README.md file and uploaded the logo picture

2020-11-13 12:44 UTC, shakedch commented
Fixes: #3

2020-11-15 13:16 UTC, bardielle commented on README.md
> +Project Groot is an open-source garden management system. In its core, Project Groot is a regular automatic plant growing system: it reads data from humidity and light sensors and decides when to giv
Update the description here.... 
your project name is not Groot....

2020-11-15 13:17 UTC, bardielle requested changes
Please add the relevant issue to that PR

2020-11-17 08:25 UTC, bardielle commented
@Varditli ?

2020-11-17 10:44 UTC, Varditli commented
Fixes: #3

2020-11-17 11:18 UTC, bardielle commented
@Varditli Please look at my comment - fix the README file with the relevant project description

2020-11-18 14:15 UTC, closed without merging